# -*- coding: utf-8 -*-
"""Assignment4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1136Ie2N3QfO7QhBT2O6bi0pQPxS2mG2l

Q1: Create a class called BankAccount that has four attributes: bankname, firstname,
lastname, and balance.
The default balance should be set to 0.
In addition, create ...
● A method called deposit() that allows the user to make deposits into their balance.
● A method called withdrawal() that allows the user to withdraw from their balance.
● Withdrawal may not exceed the available balance. Hint: consider a conditional argument
in your withdrawal() method.
● Use the __str__() method in order to display the bank name, owner name, and current
balance.
● Make a series of deposits and withdrawals to test your class.
"""

# Create a class called BankAccount that has four attributes: bankname, firstname, lastname, and balance default set to zero
class BankAccount:
    def __init__(self, bankname, firstname, lastname, balance=0):
        self.bankname = bankname
        self.firstname = firstname
        self.lastname = lastname
        self.balance = balance
# deposit() that allows the user to make deposits into their balance.
    def deposit(self):
        amount = float(input("Enter deposit amount: $"))
        if amount > 0:
            self.balance += amount
            print(f"Deposited ${amount:.2f}. New balance: ${self.balance:.2f}")
        else:
            print("Deposit amount must be greater than zero.")
# withdrawal() that allows the user to withdraw from their balance
    def withdrawal(self):
        amount = float(input("Enter withdrawal amount: $"))
# Withdrawal may not exceed the available balance. consider a conditional argument in your withdrawal() method. If amount is greater than balance.
        if amount > self.balance:
            print(f"Declined: Withdrawal of ${amount:.2f} exceeds available balance (${self.balance:.2f}).")
        elif amount <= 0:
            print("Withdrawal amount must be greater than zero.")
        else:
            self.balance -= amount
            print(f"Withdrew ${amount:.2f}. Remaining balance: ${self.balance:.2f}")
# the str() method in order to display the bank name, owner name, and current balance
    def __str__(self):
        return f"Bank: {self.bankname} | Owner: {self.firstname} {self.lastname} | Balance: ${self.balance:.2f}"


# --- Make a series of deposits and withdrawals to test your class because of input used abave ---

# 1. Create a bankacount transaction
account = BankAccount("Chase", "Pricilla", "Nakyazze")
print(account)

# 2. A series of deposit user input
account.deposit()
account.deposit()


# 3. A series of Withdrawal user input
account.withdrawal()
account.withdrawal()


# 4. View summary of what account actions were taken.
print(account)



"""Create a class Box that has attributes length and width that takes values for length
and width upon construction (instantiation via the constructor).

In addition, create…
● A method called render() that prints out to the screen a box made with asterisks of
length and width dimensions
● A method called invert() that switches length and width with each other
● Methods get_area() and get_perimeter() that return appropriate geometric calculations
● A method called double() that doubles the size of the box. Hint: Pay attention to return
value here.
● Implement __eq__ so that two boxes can be compared using ==. Two boxes are equal if
their respective lengths and widths are identical.
● A method print_dim() that prints to screen the length and width details of the box
● A method get_dim() that returns a tuple containing the length and width of the box
● A method combine() that takes another box as an argument and increases the length
and width by the dimensions of the box passed in
● A method get_hypot() that finds the length of the diagonal that cuts through the middle
● Instantiate 3 boxes of dimensions 5,10 , 3,4 and 5,10 and assign to variables box1,
box2 and box3 respectively
● Print dimension info for each using print_dim()
● Evaluate if box1 == box2, and also evaluate if box1 == box3, print True or False to the
screen accordingly
● Combine box3 into box1 (i.e. box1.combine())
● Double the size of box2
● Combine box2 into box1

"""

import math

class Box:
  def __init__(self, length, width):
        self.length = length
        self.width = width
 # render() that prints out to the screen a box made with asterisks of length and width dimensions
  def render(self):
       for _ in range(self.width):
        print("*" * self.length)



#● A method called invert() that switches length and width with each other
  def invert(self):
        """Swaps length and width."""
        self.length, self.width = self.width, self.length
# Methods get_area() and get_perimeter() that return appropriate geometric calculations
  def get_area(self):
        """Returns the area of the box."""
        return self.length * self.width

  def get_perimeter(self):
        """Returns the perimeter of the box."""
        return 2 * (self.length + self.width)
#A method called double() that doubles the size of the box. Hint: Pay attention to return value here.
  def double(self):
        """Doubles both length and width."""
        self.length *= 2
        self.width *= 2
#Implement __eq__ so that two boxes can be compared using ==. Two boxes are equal if their respective lengths and widths are identical.
  def __eq__(self, other):
        """Checks if two boxes have identical length and width."""
        if isinstance(other, Box):
            return self.length == other.length and self.width == other.width
        return False
#A method print_dim() that prints to screen the length and width details of the box
  def print_dim(self):
        """Prints the length and width dimensions."""
        print(f"Length: {self.length}, Width: {self.width}")
# A method get_dim() that returns a tuple containing the length and width of the box
  def get_dim(self):
        """Returns the dimensions as a tuple (length, width)."""
        return (self.length, self.width)
#A method combine() that takes another box as an argument and increases the length and width by the dimensions of the box passed in
  def combine(self, other):
        """Adds dimensions of another box to this box."""
        if isinstance(other, Box):
            self.length += other.length
            self.width += other.width
#A method get_hypot() that finds the length of the diagonal that cuts through the middle
  def get_hypot(self):
        """Calculates and returns the diagonal / hypotenuse."""
        return math.hypot(self.length, self.width)

#Instantiate 3 boxes of dimensions 5,10 , 3,4 and 5,10 and assign to variables box1, box2 and box3 respectively
box1 = Box(5, 10)
box2 = Box(3, 4)
box3 = Box(5, 10)

#Print dimension info for each using print_dim()
print("Initial Dimensions:")
print("Box 1:", end=" "); box1.print_dim()
print("Box 2:", end=" "); box2.print_dim()
print("Box 3:", end=" "); box3.print_dim()

#Evaluate if box1 == box2, and also evaluate if box1 == box3, print True or False to the screen accordingly
print("\n Evaluation Checks:")
print("box1 == box2:", box1 == box2)  # False
print("box1 == box3:", box1 == box3)  # True

#Combine box3 into box1 (i.e. box1.combine())
box1.combine(box3)
print("Box 1 after combining Box 3:", end=" "); box1.print_dim()

#Double the size of box2
box2.double()
print("Box 2 after doubling:", end=" "); box2.print_dim()

#Combine box2 into box1
box1.combine(box2)
print("Box 1 after combining Box 2:", end=" "); box1.print_dim()