# -*- coding: utf-8 -*-
"""Copy of Pricilla Nakyazze InClassActivity1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19iB6ZJ16ImDRenOHMpgSG2dScZJQPh2c

**Objective:**
Students will work in groups (2-3) to answer questions on python basics.

**Question 1**

The program below is supposed to:

* Ask for three quiz scores
* Calculate the average
* Print a message if the average is passing (70 or higher)

**Fix all errors and add comments explaining your changes.**
"""

PASSING_SCORE = 70

quiz1 = float(input("Enter quiz 1 score: "))
quiz2 = float(input("Enter quiz 2 score: "))
quiz3 = float(input("Enter quiz 3 score: "))

average = quiz1 + quiz2 + quiz3 / 3

print("Quiz average:", average)

if average >= PASSING_SCORE:
   print("You passed the class!")

"""**Checklist:**

 * All inputs use the correct data type
 * Average is calculated correctly
 * if statement works
 * Comments explain fixes

---
**Question 2: Hourly Pay Calculator**

* Write a program that:
* Asks the user for the number of hours worked
* Asks for their hourly rate
* Calculates total pay
* Prints the result
"""

# Prompt the user for hours worked and hourly rate
hours_worked = float(input("Enter hours worked: "))
pay_rate = float(input("Enter hourly rate: "))

# Calculate total pay
total_pay = hours_worked * pay_rate

# Display the result formatted to two decimal places
print(f"Total pay: ${total_pay:.2f}")

"""---
**Part 3: Simple Decision Program**

Concepts: conditionals, comparison operators

**Write a program that:**

* Asks the user for a number

**Prints:**
 * "Positive" if the number is greater than 0
 * "Negative" if the number is less than 0
 * "Zero" if the number is exactly 0
"""

# Prompt the user to enter a number and convert it to a float
number = float(input("Enter a number: "))

# Check whether the number is positive, negative, or zero
if number > 0:
    print("Positive")
elif number < 0:
    print("Negative")
else:
    print("Zero")

"""---
**Question 4**

**Scenario**

An online store charges shipping based on the total cost of an order:

* Orders under $50 → $10 shipping

* Orders $50–$99.99 → $5 shipping

* Orders $100 or more → Free shipping

**Task**

Write a program that:
* Asks the user for the total cost of their order
* Determines the shipping cost

Prints:

* Order total
* Shipping cost
* Final total (order + shipping)


**Bonus**

* If the order total is negative, print an error message
* Format output to two decimal places
"""

# Ask the user for the order total
order_total = float(input("Enter order total: "))

# Check for invalid negative order total
if order_total <= 0:
    print("Error: Order total cannot be 0 or negative.")
else:
    # Determine shipping cost
    if order_total < 50:
        shipping_cost = 10.00
    elif order_total < 100:
        shipping_cost = 5.00
    else:
        shipping_cost = 0.00

    # Calculate final total
    final_total = order_total + shipping_cost

    # Print results formatted to two decimal places
    print(f"Order total: ${order_total:.2f}")
    print(f"Shipping cost: ${shipping_cost:.2f}")
    print(f"Final total: ${final_total:.2f}")

"""---
**Question 5**

You are analyzing exam data for a small class.

Write a program that:

* Asks the user to enter four exam scores

* Calculates:

  * The average score
  * The highest score
  * The lowest score
  * Prints a short data summary
"""

# Ask for four exam scores
score1 = float(input("Enter exam score 1: "))
score2 = float(input("Enter exam score 2: "))
score3 = float(input("Enter exam score 3: "))
score4 = float(input("Enter exam score 4: "))

# Calculate average
average_score = (score1 + score2 + score3 + score4) / 4

# Find highest and lowest scores
highest_score = max(score1, score2, score3, score4)
lowest_score = min(score1, score2, score3, score4)

# Print summary
print("\n   Exam Data Summary    ")
print(f"Average Score: {average_score:.2f}")
print(f"Highest Score: {highest_score:.2f}")
print(f"Lowest Score:  {lowest_score:.2f}")